nail_studio/nail_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from main_page.views import bad_request
from nail_studio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('sign_up/', include('sign_up.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('favicon.ico', RedirectView.as_view(url='static/favicons/favicon.ico')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = bad_request

nail_studio/sign_up/urls.py
from django.conf.urls.static import static
from django.urls import path

from nail_studio import settings
from . import views

urlpatterns = [
    path('', views.sign_up, name='sign_up'),
    path('validate_date/', views.validate_date, name='validate_date'),
    path('get_additional_service/', views.get_additional_service, name='get_additional_service'),
    path('create_obj_of_sign_up/', views.create_obj_of_sign_up, name='create_obj_of_sign_up'),
    path('finish/<int:pk>/', views.sign_up_finish, name='sign_up_finish'),
    path('error/', views.sign_up_error, name='sign_up_error'),
    path('delete_obj_of_sign_up/<int:pk>/', views.delete_obj_of_sign_up, name='delete_obj_of_sign_up'),
    path('create_calendar_event/', views.create_calendar_event, name='create_calendar_event'),
    path('<service>/', views.sign_up, name='sign_up_with_args'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nail_studio/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    path("all_past_sign_ups/", views.all_past_sign_ups, name="all_past_sign_ups"),
    path("ban_list/", views.ban_list, name="ban_list"),
    path("ban_user/", views.ban_user, name="ban_user"),
    path("unban_list/", views.unban_list, name="unban_list"),
    path("unban_user/", views.unban_user, name="unban_user"),
    path("delete_sign_up/<int:pk>/", views.delete_sign_up, name="delete_sign_up"),
    path('future_sign_ups/', views.future_sign_ups, name="f_sign_ups"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path("future_sign_ups/<int:pk>/", views.future_sign_up, name="future_sign_up"),
    path('flash_call/', views.flash_call, name='flash_call'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('login_not_staff/', views.login_not_staff, name='login_not_staff'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("master_p_sign_ups/", views.master_p_sign_ups, name="master_p_sign_ups"),
    path("move_sign_up/<int:pk>/", views.move_sign_up, name="move_sign_up"),
    path('past_sign_ups/', views.past_sign_ups, name="p_sign_ups"),
    path('personal-account/', views.personal_account, name="personal-account"),
    path('phone-check/', views.phone_check, name="phone_check"),
    path('register/', views.register, name='register'),
    path('refactor/', views.refactor_personal_data, name="refactor_personal_data"),
    path('sign_up/<int:pk>/', views.sign_up, name="sign_up"),
    path("week_future_sign_ups/", views.week_future_sign_ups, name="week_future_sign_ups"),
]

nail_studio/sign_up/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms.utils import ErrorList

from .models import PersonDataAndDate, Service, Time, AdditionalService
from main_page.models import ServiceForHtml


class SignUpErrorList(ErrorList):
    def __str__(self):
        return self.as_text()


class ServiceChoiceField(forms.ModelChoiceField):
    def to_python(self, value):
        return Service.objects.get_or_create(service=value)[0]


class SignUpForm(forms.Form):
    service = ServiceChoiceField(queryset=ServiceForHtml.objects.all(),
                                 empty_label='Выберите услугу',
                                 to_field_name='service',
                                 label='Услуга',
                                 widget=forms.Select(attrs={'id': "service"})
                                 )

    add_service = forms.MultipleChoiceField(
        choices=[(i.pk, i) for i in AdditionalService.objects.all()],
        # choices=[(0, 'Снятие чужой работы'), (1, 'Дизайн'),
        #          (2, 'Парафинотерапия')],
        label='Доп. услуга',
        required=False
    )
    # add_service = forms.MultipleChoiceField(choices=[i.add_service for i in AdditionalService.objects.all()])

    person_name = forms.CharField(label='Ф.И.О', widget=forms.TextInput(attrs={'name': "person-name",
                                                                               'id': "person-name",
                                                                               'placeholder': "Иванов Иван Иванович"}))
    phone_number = forms.CharField(label='Номер телефона',
                                   max_length=18,
                                   widget=forms.TextInput(attrs={
                                       'name': "phone-number",
                                       'id': "phone-number",
                                       'data-tel-input': True
                                   }))

    date = forms.DateField(widget=forms.DateInput(attrs={'type': "date",
                                                         'name': "date",
                                                         'id': "date"
                                                         }))

    time = forms.ModelChoiceField(queryset=Time.objects.all(),
                                  widget=forms.RadioSelect(attrs={
                                      'data-time-input': True,
                                      'name': "time",
                                      'class': "real-radio-time"
                                  }))

    def clean_person_name(self):
        name = self.cleaned_data['person_name']
        name_split = re.findall(r'[А-Я][а-я]+', name)
        if len(name_split) < 3:
            raise ValidationError('Имя в неверном формате')
        return name_split

    def clean_time(self):
        p = PersonDataAndDate.objects.filter(date=self.cleaned_data['date'])
        lst = []
        for i in p:
            lst.append(i.time)
        time = self.cleaned_data['time']
        if time in lst:
            raise ValidationError('К сожалению это время уже занято')
        return time


class SignUpAdminForm(forms.ModelForm):
    class Meta:
        model = PersonDataAndDate
        fields = ['service', 'additional_service', 'last_name', 'first_name', 'patronymic', 'phone_number', 'date',
                  'time', 'user_id']

    def clean_time(self):
        persons_qs = PersonDataAndDate.objects.filter(date=self.cleaned_data['date'])
        busy_time_lst = []
        for person in persons_qs:
            if self.initial:
                if person.time.pk == self.initial['time']:
                    continue
            busy_time_lst.append(person.time)
        new_time = self.cleaned_data['time']
        if new_time in busy_time_lst:
            raise ValidationError('К сожалению это время уже занято')
        return new_time

nail_studio/users/forms.py
import re

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.forms.utils import ErrorList
from django.utils.translation import gettext_lazy as _

from sign_up.models import Time, PersonDataAndDate


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input',
        "data-tel-input": "",
        'type': "tel"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    error_messages = {
        "invalid_login": "Пожалуйста, введите правильные номер телефона и пароль. Пароль может быть чувствителен к "
                         "регистру.",
        "inactive": _("This account is inactive."),
    }

    def clean_username(self):
        phone_number: str = self.cleaned_data["username"]
        if phone_number[0] == '8':
            phone_number = phone_number.replace('8', '+7')
        phone_number = re.sub(r"\s\W|\W\s|-", "", phone_number)
        return phone_number


class MoveSignUpErrorList(ErrorList):
    def __str__(self):
        return self.as_text()


class MoveSignUp(forms.Form):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': "date",
                                                         'name': "date",
                                                         'id': "date"
                                                         }))

    time = forms.ModelChoiceField(queryset=Time.objects.all(),
                                  widget=forms.RadioSelect(attrs={
                                      'data-time-input': True,
                                      'name': "time",
                                      'class': "real-radio-time"
                                  }))

    def clean_time(self):
        p = PersonDataAndDate.objects.filter(date=self.cleaned_data['date'])
        lst = []
        for i in p:
            lst.append(i.time)
        time = self.cleaned_data['time']
        if time in lst:
            raise ValidationError('К сожалению это время уже занято')
        return time

nail_studio/sign_up/views.py
import datetime
import json

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render

from integrations.google.calendar.calendar_client import GoogleCalendar
from integrations.yookassa.payments import YandexPayment
from main_page.models import ServiceForHtml
from . import models
from django.views.decorators.csrf import csrf_exempt

from .forms import SignUpForm, SignUpErrorList
from .models import Time


def sign_up(request, service=None):
    """
        Собирает в список даты из базы данных, у которых 3 времени,
        и из таблицы отключенные даты, и отправляет в context.
        При post запросе создает экземпляр модели записи
        """
    list_of_date = models.DisabledDates.objects.get_disabled_dates()
    service_html = ServiceForHtml.objects.all()
    personal_data = {}

    if request.method == 'POST':
        form = SignUpForm(request.POST, error_class=SignUpErrorList)
        if form.is_valid():
            cd = form.cleaned_data

            data = {
                'user_is_auth': request.user.is_authenticated,
                'last_name': cd['person_name'][0],
                'first_name': cd['person_name'][1],
                'patronymic': cd['person_name'][2],
                'phone_number': cd['phone_number'],
                'year': int(cd['date'].strftime("%Y")),
                'month': int(cd['date'].strftime("%m")),
                'day': int(cd['date'].strftime("%d")),
                'time': cd['time'].pk,
                'service': cd['service'].pk,
                'add_services_id': cd['add_service']
            }
            response = {'data': data}
            if not request.user.is_authenticated or not request.user.userplus.not_baned:
                prepayment = ServiceForHtml.objects.get(service=cd['service'].service).prepayment

                person_name = f"{data['last_name']} {data['first_name']} {data['patronymic']}"

                payment = YandexPayment()
                payment_response = payment.create_payment(prepayment, cd['service'].service, data['phone_number'],
                                                          person_name, request.user.is_authenticated, request.user.pk)

                data['payment_id'] = payment_response.id
                confirmation_token = payment_response.confirmation.confirmation_token

                response['confirmation_token'] = confirmation_token

            return JsonResponse(response)

    else:
        if request.user.is_authenticated:
            person_name = (request.user.last_name + " " + request.user.first_name + " " +
                           request.user.userplus.patronymic)
            if request.user.username[1:2] == "7":
                phone_number = (request.user.username[:2] + " (" + request.user.username[2:5] + ") " +
                                request.user.username[5:8] + "-" + request.user.username[8:10] + "-" +
                                request.user.username[10:])
            else:
                phone_number = request.user.username

            personal_data['person_name'] = person_name
            personal_data['phone_number'] = phone_number

            form = SignUpForm(error_class=SignUpErrorList)
        else:
            form = SignUpForm(error_class=SignUpErrorList)

    context = {
        "data": personal_data,
        'dates': list_of_date,
        'service': service,
        'form': form,
        'ServiceForHtml': service_html,
    }

    return render(request, 'sign_up/record.html', context)


@csrf_exempt
def create_obj_of_sign_up(request):
    data = json.loads(request.body)
    date = datetime.date(data['year'], data['month'], data['day'])
    try:
        payment = data['payment_id']
    except KeyError:
        payment = None

    person_name = models.PersonDataAndDate.objects.create(
        last_name=data['last_name'],
        first_name=data['first_name'],
        patronymic=data['patronymic'],
        phone_number=data['phone_number'],
        date=date,
        time=models.Time.objects.get(pk=data['time']),
        service=models.Service.objects.get(pk=data['service']),
        payment_id=payment,
        user_id=request.user if request.user.is_authenticated else None
    )
    if models.PersonDataAndDate.objects.filter(date=date).count() >= models.Time.objects.count():
        models.DisabledDates.objects.create(start_date=date, creator_is_human=False)

    for service_id in data['add_services_id']:
        add_service = models.AdditionalService.objects.get(id=int(service_id))
        person_name.additional_service.add(add_service)

    return JsonResponse({'pk': str(person_name.pk)})


@csrf_exempt
def validate_date(request):
    """
    При нажатии на день в календаре приходит дата в формате json
    При повторном нажатии на день запрос приходит, но без даты
    Эта функция, при отсутствии даты, возвращает json со словарем, в котором
    время(строка) и булево значение (все в True)(True - время занято, False - нет).
    Если дата есть, то функция запрашивает данную дату из базы данных, если такая имеется,
    то она ставит значения в True тому времени, которое находит
    """
    # Приходит дата с js в формате json (ГГГГ-ММ-ДД)
    date = json.loads(request.body)
    # Проверка на то, есть ли дата в запросе
    try:
        date = date[0]
    # Если даты нет, то отправляю объект, который деактивирует все кнопки
    except IndexError:
        times = Time.objects.all().count()
        res = {}
        for i in range(times):
            res[str(i)] = True
        return JsonResponse(res)
    year, month, day = date.split('-')
    select_day = datetime.date(int(year), int(month), int(day))

    times = Time.objects.all()
    response = {}
    s_ups = models.PersonDataAndDate.objects.filter(date=select_day)
    for i in range(times.count()):
        if s_ups:
            for s_up in s_ups:
                if s_up.time == times[i]:
                    response[str(i)] = True
                    break
                else:
                    response[str(i)] = False
        else:
            response[str(i)] = False

    # for s_up in models.PersonDataAndDate.objects.filter(date=select_day):
    #     response[str(s_up.time.pk)] = True

    return JsonResponse(response)


def get_additional_service(request):
    add_services = models.AdditionalService.objects.all()
    response = {}
    for service in add_services:
        response[str(service.pk)] = service.add_service
    return JsonResponse(response)


def sign_up_finish(request, pk):
    person_name = models.PersonDataAndDate.objects.get(pk=pk)
    date = person_name.date.strftime('%d.%m')
    time = person_name.time.time.strftime('%H:%M')
    context = {
        'pk': pk,
        'date': date,
        'time': time,
        'name': person_name.first_name
    }
    return render(request, 'sign_up/record_finish.html', context)


@csrf_exempt
def create_calendar_event(request):
    pk = json.loads(request.body)

    person_name = models.PersonDataAndDate.objects.get(pk=pk)
    additional_services = person_name.additional_service.all()
    calendar = GoogleCalendar()
    date = person_name.date.strftime('%Y-%m-%d')
    time = person_name.time.time
    service_for_calendar = person_name.service.service
    description = (
        f"{person_name.phone_number} "
        f"{person_name.last_name} "
        f"{person_name.first_name} "
        f"{person_name.patronymic}"
    )

    h, m = ServiceForHtml.objects.get(service=service_for_calendar).get_time_to_comp()

    if additional_services:
        for service in additional_services:
            service_for_calendar += f'\n\t+{service}'

    calendar.add_event(date=date, time=time, service=service_for_calendar, description=description, hour=h, minute=m)

    return HttpResponse(status=200)


def sign_up_error(request):
    return render(request, 'sign_up/error.html')


def delete_obj_of_sign_up(request, pk):
    try:
        models.PersonDataAndDate.objects.get(pk=pk).delete()
    except:
        return HttpResponse(status=400)
    else:
        return HttpResponse(status=200)

nail_studio/users/templates/users/future_sign_up.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
    <link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
    <link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
    <meta name="msapplication-TileColor" content="#39b329">
    <meta name="theme-color" content="#39b329">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/future_sign_up.css' %}">

    <title>Запись</title>
</head>
<body>
    <div class="container">
        <button class="exit" onclick="location.href='{% url 'users:f_sign_ups' %}'"></button>
        <h1>{{ sign_up.date }}
            в {{ sign_up.time }}
        </h1>
        <label for="service">Услуга</label>
        <p id="service">{{ sign_up.service }}</p>
        <label for="add-serv">Дополнительные услуги</label>
        <span id="add-serv">
            <ul>
                {% for add_serv in sign_up.additional_service.all %}
                <li>{{ add_serv }}</li>
                {% endfor %}
            </ul>
        </span>
        {% if amount_value %}
            <label for="amount_value">Предоплата</label>
            <p id="amount_value">{{ amount_value }}</p>
        {% endif %}
        <div class="wrap-button">
            <button type="button" class="move" onclick="location.href='{% url 'users:move_sign_up' pk %}'"
            {% if less_than_a_day %}
                disabled
            {% endif %}
            >Перенести</button>
            <button type="button" class="cancel" onclick="location.href='{% url 'users:delete_sign_up' pk %}'"
            {% if less_than_a_day %}
                disabled
            {% endif %}
            >Отменить</button>
        </div>
        {% if less_than_a_day %}
            <p class="text-less_than_a_day">Отменить или перенести запись можно не позже 24ч. до неё</p>
        {% endif %}
    </div>
</body>
</html>

nail_studio/users/templates/users/login.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="preconnect" href="https://fonts.googleapis.com">
	    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
    
        <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
        <link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
        <link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
        <link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
        <meta name="msapplication-TileColor" content="#39b329">
        <meta name="theme-color" content="#39b329">

        {% load static %}
        <link rel="stylesheet" href='{% static "users/css/login.css" %}'>
        <script src="{% static 'sign_up/js/phoneinput.js' %}"></script>
    
        <title>Авторизация</title>
    </head>
<body>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="container">
            <div class="logo">
                <a class="logo-link" href="{% url 'main_page' %}">
                    <img class="site_logo" src="{% static 'main_page/images/logo.png' %}" width="60" height="60">
                    <p class="logo-link-text">Polina Nail</p>
                </a>
            </div>
            <span style="color: red; font-family: Arial;">{{ form.non_field_errors }}</span>
            <p class="label" >Номер телефона</p>
            <div class="phone-number">
                {{ form.username }}
            </div>
            <span style="color: red; font-family: Arial;">{{ form.username.errors }}</span>
            <p class="label" >Пароль</p>
            <div class="password">
                {{ form.password }}
            </div>
            <div class="foget-password">
                <a id="foget-password" href="{% url 'users:forgot_password' %}">Не помню пароль</a>
            </div>
            <span style="color: red; font-family: Arial;">{{ form.password.errors }}</span>
            <div class="button-wrap">
                <button type="submit" class="button">Войти</button>
            </div>
            <div class="button-wrap">
                <button type="button" class="button button-reg" onclick="location.href='{% url 'users:register' %}'">Зарегестрироваться</button>
            </div>
        </div>
    </form>
</body>
</html>

nail_studio/users/templates/users/master_personal_account.html
<!doctype html>
<html lang=ru>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/personal_account.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/master_personal_account.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
    <link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
    <link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
    <meta name="msapplication-TileColor" content="#39b329">
    <meta name="theme-color" content="#39b329">

    <title>Личный кабинет</title>
</head>
<body>
<div>
    <div class="logo">
        <a class="logo-link" href="{% url 'main_page' %}">
            <img class="site_logo" src="{% static 'main_page/images/logo.png' %}" width="60" height="60">
            <p class="logo-link-text">Polina Nail</p>
        </a>
    </div>
    <h1>Личный кабинет мастера</h1>

    <div class="wrapper-block wrapper-button button-transform">
        <a class="link future-sign-up" href="{% url 'users:week_future_sign_ups' %}"">Предстоящие записи</a>
    </div>

    <div class="wrapper-block wrapper-button button-transform">
        <a class="link past-sign-up" href="{% url 'users:master_p_sign_ups' %}">История записей</a>
    </div>

    <div class="wrapper-block wrapper-button button-transform">
        <a href="/admin/" class="link new-sign-up">Администирование</a>
    </div>

    <div class="wrapper-block wrapper-button button-transform">
        <a href="{% url 'users:ban_list' %}" class="link ban-list">Бан-лист пользователей</a>
    </div>

    <div class="wrapper-block wrapper-button disabled">
        <a href="#" class="link stats link-dis">Статистика</a>
    </div>

    <div class="wrapper-block wrapper-button disabled">
        <a href="#" class="link notifications link-dis">Настроить уведомления</a>
    </div>

</div>
<div class="wrap-exit">
    <a class="exit" href="{% url "users:logout" %}">Выйти из аккаунта</a>
</div>

</body>
</html>

nail_studio/users/templates/users/personal_account.html
 <!doctype html>
<html lang=ru>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href='{% static "users/css/personal_account.css" %}'>
    <script src="{% static 'users/js/help_button.js' %}" defer></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
	<link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
	<link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
	<link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
	<meta name="msapplication-TileColor" content="#39b329">
	<meta name="theme-color" content="#39b329">

    <title>Личный кабинет</title>
</head>
<body>
    <div>
        <div class="logo">
            <a class="logo-link" href="{% url 'main_page' %}">
                <img class="site_logo" src="{% static 'main_page/images/logo.png' %}" width="60" height="60">
                <p class="logo-link-text">Polina Nail</p>
            </a>
        </div>
        <h1>Личный кабинет</h1>
        <div class="wrapper-block">
            <span id="edit">
                Персональные данные
                <button id="edit-button" class="button-transform" onclick="location.href='{% url 'users:refactor_personal_data' %}'"></button>
            </span>
            <div class="block-of-data">
                <p id="last-name">Фамилия</p>
                <span class="data">{{ last_name }}</span>
            </div>
            <hr>
            <div class="block-of-data">
                <p id="first-name">Имя</p>
                <span class="data">{{ first_name }}</span>
            </div>
            <hr>
            <div class="block-of-data">
                <p id="patronymic">Отчество</p>
                <span class="data">{{ patronymic }}</span>
            </div>
            <hr>
            <div class="block-of-data">
                <p>Телефон</p>
                <span class="data">{{ phone_number }}</span>
            </div>
        </div>

        <div class="wrapper-block wrapper-button button-transform">
            <a href="{% url "sign_up" %}" class="link new-sign-up">Записаться на услугу</a>
        </div>

        <div class="wrapper-block wrapper-button button-transform">
            <a class="link future-sign-up" href="{% url 'users:f_sign_ups' %}">Предстоящие записи</a>
        </div>

        <div class="wrapper-block wrapper-button button-transform">
            <a class="link past-sign-up" href="{% url 'users:p_sign_ups' %}">История записей</a>
        </div>

        <div class="wrapper-block wrapper-button disabled">
            <a href="#" class="link notifications link-dis">Настроить уведомления</a>
        </div>

        <div class="wrapper-block wrapper-button button-transform">
            <button class="link help">Помощь</button>
        </div>

        <div class="wrapper-block wrapper-button button-transform">
            <a class="link exit-link" href="{% url "users:logout" %}">Выйти из аккаунта</a>
        </div>

        <div id="modal" class="modal">
            <div class="modal-content">
                <div style="position: relative;height: 50px;">
                    <button class="close"></button>
                </div>
                <button class="modal-btn" onclick="location.href='https://wa.me/79041465797?text=Нужна%20помощь%20по%20сайту'">Вопрос мастеру</button>
                <button class="modal-btn" onclick="location.href='https://wa.me/79021790017?text=Нужна%20помощь%20по%20сайту'">Вопрос програмисту</button>
            </div>
        </div>

    </div>
</body>
</html>