nail_studio/main_page/urls.py
from django.conf.urls.static import static
from django.urls import path

from nail_studio import settings
from . import views


urlpatterns = [
    path('', views.index, name='main_page'),
    path('privacy/', views.privacy, name='privacy'),
    path('manual_user/', views.manual_user, name='manual_user')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nail_studio/nail_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from main_page.views import bad_request
from nail_studio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('sign_up/', include('sign_up.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('favicon.ico', RedirectView.as_view(url='static/favicons/favicon.ico')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = bad_request

nail_studio/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    path("all_past_sign_ups/", views.all_past_sign_ups, name="all_past_sign_ups"),
    path("ban_list/", views.ban_list, name="ban_list"),
    path("ban_user/", views.ban_user, name="ban_user"),
    path("unban_list/", views.unban_list, name="unban_list"),
    path("unban_user/", views.unban_user, name="unban_user"),
    path("delete_sign_up/<int:pk>/", views.delete_sign_up, name="delete_sign_up"),
    path('future_sign_ups/', views.future_sign_ups, name="f_sign_ups"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path("future_sign_ups/<int:pk>/", views.future_sign_up, name="future_sign_up"),
    path('flash_call/', views.flash_call, name='flash_call'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('login_not_staff/', views.login_not_staff, name='login_not_staff'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("master_p_sign_ups/", views.master_p_sign_ups, name="master_p_sign_ups"),
    path("move_sign_up/<int:pk>/", views.move_sign_up, name="move_sign_up"),
    path('past_sign_ups/', views.past_sign_ups, name="p_sign_ups"),
    path('personal-account/', views.personal_account, name="personal-account"),
    path('phone-check/', views.phone_check, name="phone_check"),
    path('register/', views.register, name='register'),
    path('refactor/', views.refactor_personal_data, name="refactor_personal_data"),
    path('sign_up/<int:pk>/', views.sign_up, name="sign_up"),
    path("week_future_sign_ups/", views.week_future_sign_ups, name="week_future_sign_ups"),
]

nail_studio/main_page/models.py
from django.db import models
from django.utils import timezone


class ServiceForHtml(models.Model):
    objects = models.Manager()
    service = models.CharField(max_length=50, verbose_name='Услуга')
    time_to_comp = models.CharField(max_length=50, verbose_name='Время выполнения в часах')
    price = models.IntegerField(verbose_name='Стоимость')
    prepayment = models.IntegerField(verbose_name='Предоплата')
    filming_work = models.IntegerField(verbose_name='Снятие чужой работы')
    image = models.ImageField(upload_to='main_page/images/for_service/', verbose_name='Фото')

    def __str__(self):
        return self.service

    class Meta:
        ordering = ['id']
        verbose_name = 'Услугу, отображаемую на сайте'
        verbose_name_plural = 'Услуги, отображаемые на сайте'

    def get_time_to_comp(self):
        seconds = int(float(self.time_to_comp) * 3600)
        h = seconds // 3600
        m = seconds % 3600 // 60
        return [h, m]


class AdditionalServiceForHtml(models.Model):
    objects = models.Manager
    service = models.CharField(max_length=50, verbose_name='Услуга')
    price = models.IntegerField(verbose_name='Стоимость')

    def __str__(self):
        return self.service

    class Meta:
        ordering = ['id']
        verbose_name = 'Доп. услугу'
        verbose_name_plural = 'Доп. услуги, отображаемые на сайте'

nail_studio/main_page/views.py
import json
import datetime

from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.template import loader

from . import models
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request):
    context = {
        'additional_services': models.AdditionalServiceForHtml.objects.all(),
        'services': models.ServiceForHtml.objects.all()
    }
    return render(request, 'main_page/index.html', context)


def privacy(request):
    return render(request, 'main_page/conf.html')


def bad_request(request, exception):
    return HttpResponseBadRequest(loader.render_to_string('main_page/bad_request.html',
                                                          {'exception': exception},
                                                          request))


def manual_user(request):
    return render(request, 'main_page/manual_user.html')

nail_studio/main_page/templates/main_page/bad_request.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
	<link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
	<link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
	<link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
	<meta name="msapplication-TileColor" content="#39b329">
	<meta name="theme-color" content="#39b329">

    <title>Ошибка запроса</title>
</head>
<body style="height:100vh;display:flex;justify-content:center;align-items:center;">
<div style="font-family: Arial;">
    <h1 style="text-align:center;font-size:2rem;">Ошибка запроса</h1>
    <p style="font-size:1.5rem">{{ exception }}</p>
</div>
</body>
</html>

nail_studio/main_page/templates/main_page/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Маникюр Киренск</title>

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
	<link
  		rel="stylesheet"
  		href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
	/>

	<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

	{% load static %}
	<link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
	<link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
	<link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
	<link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
	<meta name="msapplication-TileColor" content="#39b329">
	<meta name="theme-color" content="#39b329">

	<link rel="stylesheet" type="text/css" href="{% static 'main_page/css/index.css' %}">
	<script src="{% static 'main_page/js/hamburger-button.js'%}" defer></script>
</head>
<body>

<header class="header">
	<div class="container">
		<div class="wrapper-header-link">
			<div class="wrapper-logo">
				<a href="{% url 'main_page' %}"><img class="site_logo" src="{% static 'main_page/images/logo.png' %}" width="80" height="80"></a>
			</div>

			<nav class="navigation">
				<a class="nav-link" href="#about">О себе</a>
				<a class="nav-link" href="#services">Прайс-лист</a>
				<a class="nav-link" href="#reviews">Отзывы</a>
				<a class="nav-link" href="#contacts">Контакты</a>
			</nav>
			<div class="wrapper-button-make-an-appointment">
				<div class="wrapper-icon">
					<a href="https://vk.com/kirnails"><img id="vk_logo" src="{% static 'main_page/images/vk_logo.jpg' %}" width="30" height="30"></a>
					<a href="https://chat.whatsapp.com/GQULPGO151S6nLrkp4Fkw8"><img id="wapp_logo" src="{% static 'main_page/images/wapp_logo.jpg' %}" width="30" height="30"></a>
				</div>
				<button class="button-make-an-appointment" onclick="location.href='{% url 'users:personal-account' %}'"></button>
				<div class="hamburger-button">
					<div class="hamburger-button-top"></div>
					<div class="hamburger-button-middle"></div>
					<div class="hamburger-button-bottom"></div>
				</div>
			</div>
		</div>
	</div>
</header>

<div class="intro" style="background: linear-gradient(#f7f7f7, 1%, #39B329, 80%, #f7f7f7);">
	<div id="main" class="container">
		<div class="intro__block">
			<h1>
				Мастер ногтевого сервиса
			</h1>

			<button class="button-online-req" onclick="location.href='{% url 'sign_up' %}'">
				Онлайн запись
			</button>
		</div>
	</div>
</div>

<div id="about" class="container">
	<div class="about">
		<div class="photos">
			<div class="image-wrapp">
				<img src="{% static 'main_page/images/Image(1).jpeg'%}">
				<img src="{% static 'main_page/images/Image(2).jpeg'%}">
			</div>
		</div>
		<div class="about-wrapp">
			<h4>О себе</h4>
			<p class="about-text">Молодой сертифицированный специалист, оказывающий услуги по маникюру уже на протяжении 3-х лет.<br>
				За относительно небольшую цену я предлагаю: богатую палитру цветов, материалы высокого качества, всегда обработанные инструменты перед процедурой. </p>
		</div>
	</div>
	<h4 class="text-portfolio">Некоторые из работ</h4>
	<p class="text-portfolio-vk">Больше работ вы можете найти в<br>моей группе <a href="https://vk.com/kirnails">ВКонтакте</a></p>
</div>
<div class="portfolio">
	<div class="container">
		<div class="photo-wrapp">
			<img src="{% static 'main_page/images/Image(3).jpeg'%}">
			<img src="{% static 'main_page/images/Image(4).jpg'%}">
			<img src="{% static 'main_page/images/Image(5).jpg'%}">
			<img src="{% static 'main_page/images/Image(6).jpg'%}">
			<img src="{% static 'main_page/images/Image(7).jpg'%}">
			<img src="{% static 'main_page/images/Image(8).jpg'%}">
			<img src="{% static 'main_page/images/Image(9).jpg'%}">
			<img src="{% static 'main_page/images/Image(10).jpg'%}">
			<img src="{% static 'main_page/images/Image(11).jpg'%}">
			<img src="{% static 'main_page/images/Image(12).jpg'%}">
			<img src="{% static 'main_page/images/Image(13).jpg'%}">
			<img src="{% static 'main_page/images/Image(14).jpg'%}">
			<img src="{% static 'main_page/images/Image(15).jpg'%}">
			<img src="{% static 'main_page/images/Image(16).jpg'%}">
		</div>
	</div>
</div>

<div id="services" class="container">
	<div class="services">
		<h3>Прайс-лист</h3>
		<div class="services-display">
			{% for s in services %}
				<div class="services-block">
					<img class="services-img" src="/static/{{s.image}}" width="270" height="153">
					<h2>{{ s.service }}</h2>
					<p class="text-in-service-block">{{s.time_to_comp}} ч.</p>
					<p class="text-in-service-block-120-rub">Снятие чужой работы: {{s.filming_work}} руб.</p>
					<p class="text-in-service-block">Предоплата ({{ s.prepayment }} руб.)</p>
					<p class="services-price"><b>{{ s.price }}</b> руб.</p>
					<div class="services-button-wrapper">
						<button class="services-button" onclick="location.href='{% url 'sign_up_with_args' s.service %}'">
							Записаться
						</button>
					</div>
				</div>
			{% endfor %}
		</div>

		<div class="service-on-the-side">
			{% for s in additional_services %}
				<div class="services-block" id="on-the-side">
					<h2>{{ s.service }}</h2>
					<p class="services-price" id="price-on-the-side"><b>{{ s.price }}</b> руб.</p>
					<div class="services-button-wrapper">
						<button class="services-button" onclick="location.href='{% url 'sign_up_with_args' s.service %}'">
							Записаться
						</button>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>

<div id="reviews" class="container">
	<div class="reviews">
		<h5>Отзывы клиентов</h5>
		<p class="reviews-feedback">Буду рада обратной связи.
			Отправляйте свои отзывы на <b><a style="text-decoration: none; color: #000;" href="mailto:d.pauline.w@gmail.com">d.pauline.w@gmail.com</a></b></p>
		<div class="swiper mySwiper">
			<div class="swiper-wrapper">
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="swiper-slide">-->
<!--					<div class="reviews-wrapper">-->
<!--						<div class="reviews-image"></div>-->
<!--						<div class="reviews-text">-->
<!--							<p>Все очень классно. Все понравилось. Девочка просто умница, или одним словом молодец</p>-->
<!--							<p class="reviews-user-name">Агата</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
				<div class="swiper-slide">
					<div class="reviews-wrapper">
						<div class="reviews-image"></div>
						<div class="reviews-text">
							<p>Отправляйте фотографии и делитесь впечатлениями. Здесь будем публиковать ваши отзывы</p>
							<p class="reviews-user-name">support@polina-nail.ru</p>
						</div>
					</div>
				</div>
			</div>
			<div class="swiper-pagination"></div>
			<div class="swiper-button-next"></div>
			<div class="swiper-button-prev"></div>
		</div>
		<script>
			var swiper = new Swiper('.mySwiper', {
				spaceBetween: 30,
				navigation: {
					nextEl: '.swiper-button-next',
					prevEl: '.swiper-button-prev',
				},
				pagination: {
					el: '.swiper-pagination',
				},
				mousewhell: true,
			});
		</script>
	</div>
</div>

<div id="contacts" class="contacts">
	<div class="contacts-wrapper">
		<h6>Контакты</h6>
		<p class="contacts-text">мкр.Мельничный, ул.Трудовых резервов, д.2</p>
		<p class="contacts-text">Номер телефона: <a href="tel:+79041465797">+7 (904) 146-57-97</a></p>
		<p class="contacts-text">Время работы: 10:00 — 19:00</p>
	</div>
	<div id="wrapMap">
		<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ade198439c8cc5f1ea782cbfa26aaaf85803cd3d23c0fc2c89b894e90a59e9dfd&amp;width=100%25&amp;height=500&amp;lang=ru_RU&amp;scroll=false"></script>
	</div>
</div>

<footer>
	<div class="container">
		<div class="footer-info" style="display: flex;justify-content: space-around;">
			<div>
				<p style="margin-bottom: 5px;margin-top: 0;"><a style="text-decoration: none;color: #777e89;" target="_blank" href="{% url 'manual_user' %}">Мануал по использованию сайта</a></p>
				<p style="margin-bottom: 5px;margin-top: 0;"><a style="text-decoration: none;color: #777e89;" target="_blank" href="{% url 'privacy' %}">Политика конфиденциальности</a></p>
				<p style="margin-top: 5px;"><a style="text-decoration: none;color: #777e89;" target="_blank" href="{% static 'main_page/images/sertif.png'%}">Сертификат</a></p>
			</div>
			<div>
				<span>Помощь и вопросы по сайту <b><a style="color: #777e89;" href="mailto:support@polina-nail.ru">support@polina-nail.ru</a></b></span>
				<style>
					table {
					border-collapse: collapse; /* Убираем двойные линии между ячейками */
					margin-top: 20px;
				   }
				   td, th {
					padding: 3px; /* Поля вокруг содержимого таблицы */
					border: 1px solid black; /* Параметры рамки */
				   }
				</style>
				<table style="color: #777e89;">
					<caption>Реквизиты</caption>
					<tr>
						<td>Ф.И.О.</td>
						<td>Дядина Полина Александровна</td>
					</tr>
					<tr>
						<td>ИНН</td>
						<td>383106010204</td>
					</tr>
				</table>
			</div>
		</div>
		<div style="margin-top: 20px;">&copy Все права защищены</div>
	</div>
</footer>

</body>
</html>

nail_studio/main_page/templates/main_page/manual_admin.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>

nail_studio/main_page/templates/main_page/manual_user.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="https://polina-nail.ru/static/favicons/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://polina-nail.ru/static/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://polina-nail.ru/static/favicons/favicon-16x16.png">
	<link rel="shortcut icon" type="image/png" href="https://polina-nail.ru/static/favicons/favicon.ico"/>
	<link rel="manifest" href="https://polina-nail.ru/static/favicons/site.webmanifest">
	<link rel="mask-icon" href="https://polina-nail.ru/static/favicons/safari-pinned-tab.svg" color="#39b329">
	<meta name="msapplication-TileColor" content="#39b329">
	<meta name="theme-color" content="#39b329">

    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
	<link
  		rel="stylesheet"
  		href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
	/>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main_page/css/manual_user.css' %}">
    <script src="{% static 'main_page/js/hamburger-button.js'%}" defer></script>

    <title>Мануал пользователя</title>
</head>
<body>

<header class="header">
	<div class="container">
		<div class="wrapper-header-link">
			<div class="wrapper-logo">
				<a href="{% url 'main_page' %}"><img class="site_logo" src="{% static 'main_page/images/logo.png' %}" width="80" height="80"></a>
			</div>

			<nav class="navigation">
				<div class="wrapper-nav-link"><a class="nav-link" href="#1">Как записаться на услугу</a></div>
				<div class="wrapper-nav-link"><a class="nav-link" href="#2">Как отменить или перенести запись</a></div>
				<div class="wrapper-nav-link"><a class="nav-link" href="#3">Как не потерять сайт</a></div>
			</nav>
			<div class="wrapper-button-make-an-appointment">
				<div class="wrapper-icon">
					<a href="https://vk.com/kirnails"><img id="vk_logo" src="{% static 'main_page/images/vk_logo.jpg' %}" width="30" height="30"></a>
					<a href="https://chat.whatsapp.com/GQULPGO151S6nLrkp4Fkw8"><img id="wapp_logo" src="{% static 'main_page/images/wapp_logo.jpg' %}" width="30" height="30"></a>
				</div>
				<button class="button-make-an-appointment" onclick="location.href='{% url 'sign_up' %}'">
					Записаться
				</button>
				<div class="hamburger-button">
					<div class="hamburger-button-top"></div>
					<div class="hamburger-button-middle"></div>
					<div class="hamburger-button-bottom"></div>
				</div>
			</div>
		</div>
	</div>
</header>
<div class="container-body">
    <h1>Инструкция по пользованию сайта</h1>
    <h2 id="1">Как записаться на услугу</h2>
    <dl>
        <dt>
            <div>Сперва нужно нажать кнопку "онлайн запись"</div>
        </dt>
        <dd>
            <div>
                <img src="/media/main_page/user_step1.png" width="200px">
            </div>
        </dd>
        <dt>
        <div>Либо выбрать из предложенных услуг на главной странице</div>
        </dt>
        <dd>
            <div>
                <img src="/media/main_page/user_step1(1).png" width="150px">
                <img src="/media/main_page/user_step1(2).png" width="150px">
                <img src="/media/main_page/user_step1(3).png" width="150px">
                <img src="/media/main_page/user_step1(4).png" width="150px">
            </div>
        </dd>
        <dt>
            <div>
                Далее вы будите перенаправлены на страницу записи, где нужно ввести данные и выбрать услугу
                (в случае если не выбрали её на главной странице), дату и время
            </div>
        </dt>
        <dd>
            <img src="/media/main_page/user_step2.png" width="200px">
        </dd>
        <dt>
            <div>
                После заполнения формы вы будите перенесены на страницу оплаты, где можно выбрать способы оплаты.
            </div>
        </dt>
        <dd>
            <div>Если вы уже оплачивали банковской картой и нажимали галочку запомнить карту,
                то она будет сохранена как способ оплаты</div>
            <div><img src="/media/main_page/user_step3.png" width="200px"></div>
        </dd>
        <dt>После оплаты вы будите перенаправлены на страницу успешного завершения записи</dt>
    </dl>
    <h2 id="2">Как отменить или перенести запись</h2>
    <dl>
        <dt>
            Для этого нужно написать на контактный номер,
            расположенный в разделе контакты, на главной странице сайта, в мессенджере What'sApp
        </dt>
        <dd>
            <h4>Пример сообщения</h4>
            <div>
                Здравствуйте! Пожалуйста, перенесите запись:
                <ul>
                    <li>ФИО</li>
                    <li>Номер телефона указанный при записи</li>
                    <li>Дата и время</li>
                </ul>
                на (дата и время)
            </div>
            <br>или
            <div>
                <br>Здравствуйте! Пожалуйста, отмените запись:
                <ul>
                    <li>ФИО</li>
                    <li>Номер телефона указанный при записи</li>
                    <li>Дата и время</li>
                </ul>
            </div>
        </dd>
        <dt>В случае отмены имейте ввиду что, если до записи осталось меньше 3-х дней, то предоплата не возвращается</dt>
    </dl>
    <h2 id="3">Как не потерять сайт</h2>
    <dl>
        <dt>На мобильных устройствах сайт можно закрепить на рабочем столе</dt>
        <dt><h3>На Iphone</h3></dt>
        <dd>
            <p>В браузере Safari</p>
            <img src="/media/main_page/user_save_site_iphone.jpg" width="200px">
            <img src="/media/main_page/user_save_site_iphone(1).jpg" width="200px">
        </dd>
        <dt><h3>На Android</h3></dt>
        <dd>
            <p>
                На разных устройствах процесс немного отличается, но в целом нужно нажать на три точки и добавить ярлык
                на главный экран
            </p>
            <img src="/media/main_page/user_save_site_android.png" width="290px">
        </dd>
    </dl>
</div>
</body>
</html>

nail_studio/main_page/templates/main_page/record_finish.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Завершение записи</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main_page/css/record_finish.css' %}">
</head>
<body>
<div class="placeholder">
    <p class="text">
        Вы успешно записаны.<br>
        По вопросам записи <a href="tel:+79041465797">+7_(904)_146-57-97</a><br>
        По поводу предоплаты с вами свяжутся в мессенджере WhatsApp
    </p>
    <a href="{% url 'main_page' %}" class="link-main">Вернутся на главную</a>
</div>
<script>
    requestURL = "{% url 'create_calendar_event' %}"

    function sendRequest (method, url, pk) {
        return new Promise ((resolve, reject) => {
            const xhr = new XMLHttpRequest()

            xhr.open(method, url)

            xhr.responseType = 'json'
            xhr.setRequestHeader('Content-Type', 'application/json')

            xhr.onload = () => {
                if (xhr.status >= 400) {
                    reject(xhr.response)
                } else {
                    resolve(xhr.response)
                }
            }

            xhr.onerror = () => {
                reject(xhr.response)
            }
            xhr.send(JSON.stringify(pk))
        })
    }

    document.addEventListener('DOMContentLoaded', () => {
        sendRequest('POST', requestURL, {{ pk }})
            .then(data => console.log(data))
            .catch(err => console.log(err))
    });
</script>
</body>
</html>